# Generated by Django 6.0.1 on 2026-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_order_paid_at_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
