# Generated by Django 6.0.1 on 2026-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Pay online with Razorpay'), ('COD', 'Pay on delivery')], default='RAZORPAY', max_length=10),
        ),
    ]
