# Generated by Django 6.0.1 on 2026-09-28 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('PENDING', 'Received'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Out for delivery'), ('COMPLETED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
