# Generated by Django 6.0.1 on 2026-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_product_video_user_profile_photo_productreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
